# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BL <- function(x, y, e, c, w, maxSteps, n, hatBeta, hatEta, hatAlpha, hatb, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, invSigb0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, progress) {
    .Call(`_marble_BL`, x, y, e, c, w, maxSteps, n, hatBeta, hatEta, hatAlpha, hatb, hatInvTauSq1, hatInvTauSq2, invSigAlpha0, invSigb0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, progress)
}

BLSS <- function(x, y, e, c, w, maxSteps, n, hatBeta, hatEta, hatAlpha, hatb, hatInvTauSq1, hatInvTauSq2, sg1, sg2, hatPiEta, hatPiBeta, invSigAlpha0, invSigb0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, mu0, nu0, progress) {
    .Call(`_marble_BLSS`, x, y, e, c, w, maxSteps, n, hatBeta, hatEta, hatAlpha, hatb, hatInvTauSq1, hatInvTauSq2, sg1, sg2, hatPiEta, hatPiBeta, invSigAlpha0, invSigb0, hatLambdaSqStar1, hatLambdaSqStar2, hatSigmaSq, aStar, bStar, alpha, gamma, mu0, nu0, progress)
}

RBL <- function(x, y, w, c, e, maxSteps, n, hatAlpha, hatb, hatBeta, hatEta, hatTau, hatV, hatSg1, hatSg2, invSigAlpha0, invSigb0, hatEtaSq1, hatEtaSq2, theta, r1, r, a, b, progress) {
    .Call(`_marble_RBL`, x, y, w, c, e, maxSteps, n, hatAlpha, hatb, hatBeta, hatEta, hatTau, hatV, hatSg1, hatSg2, invSigAlpha0, invSigb0, hatEtaSq1, hatEtaSq2, theta, r1, r, a, b, progress)
}

RBLSS <- function(x, y, w, c, e, maxSteps, n, hatAlpha, hatb, hatBeta, hatEta, hatTau, hatV, hatSg1, hatSg2, sg1, sg2, invSigAlpha0, invSigb0, hatEtaSq1, hatEtaSq2, theta, r1, r, a, b, hatPiBeta, hatPiEta, sh0, sh1, progress) {
    .Call(`_marble_RBLSS`, x, y, w, c, e, maxSteps, n, hatAlpha, hatb, hatBeta, hatEta, hatTau, hatV, hatSg1, hatSg2, sg1, sg2, invSigAlpha0, invSigb0, hatEtaSq1, hatEtaSq2, theta, r1, r, a, b, hatPiBeta, hatPiEta, sh0, sh1, progress)
}

